(function exposeCrossclimbData(globalScope) {
  "use strict";

  const clues = {
    ADD: "To put something together with something else.",
    AID: "Help given to someone who needs it.",
    AIR: "The invisible gas that we breathe.",
    BACK: "The rear part of something.",
    BAD: "Not good or not pleasant.",
    BAG: "A container used to carry things.",
    BALL: "A round object used in many games.",
    BAR: "A long solid piece, or a place that serves drinks.",
    BAT: "A flying animal that is active at night.",
    BED: "Furniture used for sleeping.",
    BEE: "A small insect that makes honey.",
    BELL: "A metal object that makes a ringing sound.",
    BELT: "A strip worn around the waist.",
    BEST: "Better than all the others.",
    BIG: "Large in size.",
    BIKE: "A two-wheeled vehicle powered by pedals or a motor.",
    BITE: "To cut something using your teeth.",
    BOAT: "A small vehicle used for travelling on water.",
    BOOK: "A set of written or printed pages.",
    BOOT: "A strong shoe that covers the ankle.",
    BOX: "A container with flat sides and a lid.",
    BOY: "A male child.",
    BUS: "A large road vehicle that carries passengers.",
    BUT: "A word used to show a contrast.",
    CAME: "The past form of come.",
    CAN: "To be able to do something.",
    CARD: "A small piece of thick paper used for messages or games.",
    CARE: "Attention given to keep someone or something safe.",
    CAR: "A road vehicle for a small number of people.",
    CASE: "A container, or a particular situation.",
    CASH: "Money in the form of notes and coins.",
    CAT: "A common pet that purrs.",
    CAVE: "A large natural hole in the side of a hill or mountain.",
    CHIP: "A small thin piece, or a part inside a computer.",
    CHOP: "To cut something into pieces.",
    CLIP: "A small object used to hold things together.",
    COAT: "Clothing worn over other clothes.",
    CODE: "Instructions written for a computer.",
    COLD: "Having a low temperature.",
    COME: "To move towards a place or person.",
    COOK: "To prepare food using heat.",
    COOL: "Slightly cold, or very good in informal speech.",
    COP: "An informal word for a police officer.",
    CORD: "A thick string or an electrical cable.",
    CORE: "The central or most important part of something.",
    COT: "A small, simple bed.",
    COW: "A farm animal that gives milk.",
    CUP: "A small container used for drinking.",
    CUT: "To divide something using a sharp tool.",
    DARK: "Having little or no light.",
    DASH: "To move somewhere quickly.",
    DAY: "A period of twenty-four hours.",
    DIG: "To make a hole in the ground.",
    DISH: "A plate or bowl used for serving food.",
    DOG: "A common pet that barks.",
    DOOR: "A movable panel used to enter or leave a room.",
    DOT: "A very small round mark.",
    DRY: "Not wet or containing no water.",
    DUCK: "A water bird with a broad bill.",
    EAR: "The body part used for hearing.",
    EAST: "The direction where the sun rises.",
    FACE: "The front part of the head containing the eyes, nose, and mouth.",
    FACT: "Something that is known to be true.",
    FAIL: "To not succeed or meet the required standard.",
    FAIR: "Reasonable and treating people equally.",
    FALL: "To move downwards because of gravity.",
    FAN: "A device that moves air to keep a room cool.",
    FAR: "A long distance away.",
    FARM: "Land used for growing crops or keeping animals.",
    FAST: "Moving at a high speed.",
    FEED: "To give food to a person or animal.",
    FIRE: "Flames that produce heat and light.",
    FISH: "An animal that lives and swims in water.",
    FIX: "To repair something that is broken.",
    FLIP: "To turn something over quickly.",
    FOG: "A thick cloud close to the ground.",
    FOOD: "Something that people or animals eat.",
    FOOL: "A person who behaves without good judgement.",
    FOOT: "The body part at the end of the leg.",
    FORK: "A tool with pointed ends used for eating.",
    FORM: "The shape of something, or a document to fill in.",
    FOX: "A wild animal related to a dog.",
    FREE: "Able to act without control, or costing nothing.",
    FRY: "To cook food in hot oil.",
    FUN: "Enjoyment or an activity that is enjoyable.",
    GAME: "An activity played for fun or competition.",
    GET: "To receive, obtain, or fetch something.",
    GOLD: "A valuable yellow metal.",
    GOOD: "Pleasant, useful, or of high quality.",
    GUM: "The soft flesh around the teeth.",
    GUN: "A weapon that fires bullets.",
    GYM: "A place where people exercise.",
    HAIL: "Small balls of ice that fall from clouds.",
    HAIR: "The strands that grow on a person's head.",
    HAND: "The body part at the end of the arm.",
    HARD: "Firm, solid, or difficult to do.",
    HAT: "Something worn on the head.",
    HATE: "To strongly dislike someone or something.",
    HEAD: "The top part of the body containing the face and brain.",
    HEAL: "To become healthy again after an injury.",
    HEAT: "The quality of being hot.",
    HEN: "An adult female chicken.",
    HERE: "In this place.",
    HERO: "A brave person who helps others.",
    HIRE: "To give someone a paid job.",
    HOME: "The place where a person lives.",
    HOT: "Having a high temperature.",
    JAM: "A sweet fruit spread eaten on bread.",
    JOB: "Paid work done by a person.",
    JOY: "A strong feeling of happiness.",
    KIND: "Friendly, caring, and helpful.",
    KING: "A male ruler of a country.",
    LAKE: "A large area of water surrounded by land.",
    LAST: "Coming after all the others.",
    LATE: "After the expected or correct time.",
    LEG: "The body part used for standing and walking.",
    LIFE: "The state of being alive.",
    LIKE: "To enjoy or feel positive about something.",
    LINE: "A long narrow mark or a row of people.",
    LINK: "A connection between two things.",
    LIVE: "To be alive or to have your home somewhere.",
    LOAD: "Something being carried or transported.",
    LOAN: "Money borrowed and paid back later.",
    LOCK: "A device used to keep a door or container closed.",
    LOG: "A thick piece cut from a tree.",
    LOOK: "To direct your eyes towards something.",
    LOSE: "To no longer have something, or not win.",
    LOST: "Unable to find the correct place or direction.",
    LOVE: "A strong feeling of care and affection.",
    LOW: "Not high or below the usual level.",
    LUCK: "Success caused by chance.",
    MAIL: "Letters and parcels sent through a delivery service.",
    MAIN: "Most important or largest.",
    MAN: "An adult male person.",
    MAP: "A drawing that shows places and directions.",
    MASS: "A large amount of something.",
    MAY: "A word used when something is possible.",
    MEN: "More than one adult male person.",
    MESS: "A dirty or untidy state.",
    MIND: "The part of a person that thinks and remembers.",
    MINE: "Something that belongs to me.",
    MISS: "To fail to hit, reach, or catch something.",
    MIST: "A thin cloud of tiny water drops near the ground.",
    MOAN: "To make a low sound because of pain or unhappiness.",
    MOB: "A large and often disorderly crowd.",
    MOON: "The natural object that moves around Earth.",
    MOP: "A tool used for cleaning floors.",
    MORE: "A greater amount or number.",
    MOST: "The greatest amount or number.",
    MOVE: "To change position or place.",
    MUG: "A large cup, often used for tea or coffee.",
    NAME: "The word used to identify a person or thing.",
    NET: "A material made from connected threads with spaces between them.",
    NINE: "The number that comes after eight.",
    NONE: "Not any person or thing.",
    NOSE: "The body part used for smelling and breathing.",
    NOTE: "A short written message.",
    OLD: "Having existed for a long time, or not new.",
    ODD: "Different from what is usual, or not divisible by two.",
    PAIN: "An unpleasant feeling caused by injury or illness.",
    PAIR: "Two things that belong or work together.",
    PARK: "A public green area for people to enjoy.",
    PART: "One piece of a larger whole.",
    PASS: "To succeed in a test or move beyond something.",
    PEN: "A tool used for writing with ink.",
    PET: "An animal kept at home for company.",
    PIG: "A farm animal with a short nose and curly tail.",
    PIN: "A small sharp object used to fasten things.",
    POOL: "A place built for swimming.",
    POOR: "Having very little money.",
    PORT: "A place where ships load and unload goods.",
    POST: "Letters and parcels, or a message shared online.",
    PUP: "A young dog.",
    PUT: "To place something in a particular position.",
    RACK: "A frame used for holding or storing things.",
    RAIN: "Water that falls from clouds.",
    RAT: "A small animal similar to a large mouse.",
    RATE: "A price, speed, or level measured against something.",
    RED: "The colour of blood and many stop signs.",
    RENT: "Money paid regularly to use a house or other property.",
    REST: "To relax or stop working for a while.",
    RICE: "A common grain eaten as food.",
    ROCK: "A hard natural piece of stone.",
    ROAD: "A route made for vehicles to travel on.",
    RUN: "To move quickly on foot.",
    RUG: "A small carpet used to cover part of a floor.",
    SAFE: "Protected from danger or harm.",
    SAME: "Exactly like another person or thing.",
    SAND: "Very small grains of stone found on beaches.",
    SAVE: "To keep something safe or store it for later.",
    SAY: "To speak words.",
    SEA: "A large area of salt water.",
    SEAT: "Something designed for a person to sit on.",
    SEE: "To notice something using your eyes.",
    SEND: "To make something go or be delivered somewhere.",
    SENT: "The past form of send.",
    SET: "To put something in a particular position.",
    SHIP: "A large boat used at sea.",
    SHOP: "A place where things are sold.",
    SICK: "Ill or not feeling well.",
    SINK: "A bowl with taps and a drain, usually in a kitchen or bathroom.",
    SIN: "An action considered morally wrong.",
    SIP: "To drink a small amount at a time.",
    SIT: "To rest with your body supported by a chair or the ground.",
    SIX: "The number that comes after five.",
    SITE: "A place where something is built or located.",
    SKY: "The space seen above Earth.",
    SOCK: "A soft item of clothing worn on the foot.",
    SOFT: "Easy to press and not hard.",
    SOME: "An amount or number that is not exact.",
    SOON: "After a short time.",
    SORT: "To arrange things into groups or order.",
    STAR: "A bright object seen in the night sky.",
    SUN: "The star that gives Earth light and heat.",
    TAIL: "The part at the back of an animal's body.",
    TALK: "To speak with someone.",
    TALL: "Having more than average height.",
    TEA: "A hot drink made by soaking leaves in water.",
    TELL: "To give someone information using words.",
    TEN: "The number that comes after nine.",
    TENT: "A portable shelter made from cloth.",
    TEST: "A set of questions or checks used to measure knowledge or quality.",
    TIRE: "The rubber covering around a wheel.",
    TIP: "A useful small piece of advice, or the pointed end of something.",
    TOP: "The highest part of something.",
    TOY: "An object that children play with.",
    WALK: "To move on foot at a normal speed.",
    WALL: "A solid upright structure around or inside a building.",
    WAR: "Armed fighting between countries or groups.",
    WARM: "Comfortably hot.",
    WAVE: "A raised line of water, or a movement of the hand in greeting.",
    WELL: "In a good or healthy way.",
    WEST: "The direction where the sun sets.",
    WET: "Covered with water.",
    WIND: "Moving air.",
    WIN: "To be successful in a game or competition.",
    WORD: "A single unit of language with meaning.",
    WORK: "An activity that needs effort or is done as a job.",
    YES: "A word used to agree or give a positive answer.",
    YET: "Up to the present time, or nevertheless.",
    ZERO: "The number written as 0."
  };

  function makeLadder(id, category, difficulty, words) {
    return {
      id,
      category,
      difficulty,
      startWord: words[0],
      endWord: words[words.length - 1],
      ladder: words,
      clues: words.map((word) => clues[word] || "")
    };
  }

  const crossclimbDatabase = [
    makeLadder("fresh-hat-dog", "General", "Easy", ["HAT", "CAT", "COT", "DOT", "DOG"]),
    makeLadder("fresh-man-tip", "General", "Easy", ["MAN", "MAP", "MOP", "TOP", "TIP"]),
    makeLadder("fresh-sun-car", "General", "Easy", ["SUN", "FUN", "FAN", "FAR", "CAR"]),
    makeLadder("fresh-cup-bus", "College Life", "Easy", ["CUP", "PUP", "PUT", "BUT", "BUS"]),
    makeLadder("fresh-pen-dog", "General", "Easy", ["PEN", "PIN", "PIG", "DIG", "DOG"]),
    makeLadder("fresh-red-big", "General", "Easy", ["RED", "BED", "BAD", "BAG", "BIG"]),
    makeLadder("fresh-box-sit", "Technology", "Easy", ["BOX", "FOX", "FIX", "SIX", "SIT"]),
    makeLadder("fresh-day-ten", "College Life", "Easy", ["DAY", "MAY", "MAN", "MEN", "TEN"]),
    makeLadder("fresh-sea-red", "Science", "Easy", ["SEA", "SEE", "BEE", "BED", "RED"]),
    makeLadder("fresh-sky-fry", "Movies & Pop Culture", "Easy", ["SKY", "SAY", "DAY", "DRY", "FRY"]),
    makeLadder("fresh-car-bus", "College Life", "Easy", ["CAR", "BAR", "BAT", "BUT", "BUS"]),
    makeLadder("fresh-low-tip", "General", "Easy", ["LOW", "COW", "COP", "TOP", "TIP"]),
    makeLadder("fresh-old-air", "Science", "Easy", ["OLD", "ODD", "ADD", "AID", "AIR"]),
    makeLadder("fresh-job-tip", "Movies & Pop Culture", "Easy", ["JOB", "JOY", "TOY", "TOP", "TIP"]),
    makeLadder("fresh-yes-sit", "General", "Easy", ["YES", "YET", "GET", "SET", "SIT"]),
    makeLadder("fresh-fan-gym", "College Life", "Easy", ["FAN", "FUN", "GUN", "GUM", "GYM"]),
    makeLadder("fresh-mug-fun", "General", "Easy", ["MUG", "RUG", "RUN", "SUN", "FUN"]),
    makeLadder("fresh-pet-sun", "Science", "Easy", ["PET", "PEN", "PIN", "SIN", "SUN"]),
    makeLadder("fresh-leg-dig", "General", "Easy", ["LEG", "LOG", "FOG", "DOG", "DIG"]),
    makeLadder("fresh-toy-mop", "Movies & Pop Culture", "Easy", ["TOY", "JOY", "JOB", "MOB", "MOP"]),

    makeLadder("fresh-fish-core", "General", "Medium", ["FISH", "DISH", "DASH", "CASH", "CASE", "CARE", "CORE"]),
    makeLadder("fresh-dark-soft", "General", "Medium", ["DARK", "PARK", "PART", "PORT", "SORT", "SOFT"]),
    makeLadder("fresh-word-warm", "College Life", "Medium", ["WORD", "WORK", "FORK", "FORM", "FARM", "WARM"]),
    makeLadder("fresh-hard-home", "Technology", "Medium", ["HARD", "CARD", "CARE", "CORE", "CODE", "COME", "HOME"]),
    makeLadder("fresh-rain-mail", "Science", "Medium", ["RAIN", "PAIN", "PAIR", "FAIR", "HAIR", "HAIL", "MAIL"]),
    makeLadder("fresh-sand-gold", "Science", "Medium", ["SAND", "HAND", "HARD", "CARD", "CORD", "COLD", "GOLD"]),
    makeLadder("fresh-game-code", "Technology", "Medium", ["GAME", "NAME", "SAME", "SOME", "HOME", "COME", "CODE"]),
    makeLadder("fresh-love-gold", "Marvel", "Medium", ["LOVE", "MOVE", "MORE", "CORE", "CORD", "COLD", "GOLD"]),
    makeLadder("fresh-road-soon", "Science", "Medium", ["ROAD", "LOAD", "LOAN", "MOAN", "MOON", "SOON"]),
    makeLadder("fresh-wall-main", "College Life", "Medium", ["WALL", "WALK", "TALK", "TALL", "TAIL", "MAIL", "MAIN"]),
    makeLadder("fresh-ship-flip", "Technology", "Medium", ["SHIP", "SHOP", "CHOP", "CHIP", "CLIP", "FLIP"]),
    makeLadder("fresh-king-nose", "Marvel", "Medium", ["KING", "KIND", "MIND", "MINE", "NINE", "NONE", "NOSE"]),
    makeLadder("fresh-tire-zero", "Marvel", "Medium", ["TIRE", "FIRE", "HIRE", "HERE", "HERO", "ZERO"]),
    makeLadder("fresh-line-rack", "Technology", "Medium", ["LINE", "LINK", "SINK", "SICK", "SOCK", "ROCK", "RACK"]),
    makeLadder("fresh-wind-note", "Science", "Medium", ["WIND", "MIND", "MINE", "NINE", "NONE", "NOSE", "NOTE"]),
    makeLadder("fresh-wave-home", "Movies & Pop Culture", "Medium", ["WAVE", "SAVE", "SAME", "GAME", "NAME", "CAME", "COME", "HOME"]),
    makeLadder("fresh-note-core", "General", "Medium", ["NOTE", "NOSE", "LOSE", "LOVE", "MOVE", "MORE", "CORE"]),
    makeLadder("fresh-rate-site", "College Life", "Medium", ["RATE", "LATE", "LAKE", "LIKE", "BIKE", "BITE", "SITE"]),
    makeLadder("fresh-face-mist", "General", "Medium", ["FACE", "FACT", "FAST", "LAST", "LOST", "MOST", "MIST"]),
    makeLadder("fresh-safe-same", "Technology", "Medium", ["SAFE", "SAVE", "CAVE", "CAME", "GAME", "NAME", "SAME"]),
    makeLadder("fresh-test-send", "College Life", "Medium", ["TEST", "BEST", "REST", "RENT", "TENT", "SENT", "SEND"]),
    makeLadder("fresh-fail-walk", "College Life", "Medium", ["FAIL", "TAIL", "TALL", "TELL", "WELL", "WALL", "WALK"]),
    makeLadder("fresh-coat-pool", "General", "Medium", ["COAT", "BOAT", "BOOT", "BOOK", "COOK", "COOL", "POOL"]),
    makeLadder("fresh-food-luck", "College Life", "Medium", ["FOOD", "FOOT", "BOOT", "BOOK", "LOOK", "LOCK", "LUCK"]),
    makeLadder("fresh-door-boot", "General", "Medium", ["DOOR", "POOR", "POOL", "FOOL", "FOOD", "FOOT", "BOOT"]),
    makeLadder("fresh-warm-word", "R&D", "Medium", ["WARM", "FARM", "FORM", "FORK", "WORK", "WORD"]),
    makeLadder("fresh-cold-book", "Science", "Medium", ["COLD", "GOLD", "GOOD", "FOOD", "FOOT", "BOOT", "BOOK"]),
    makeLadder("fresh-hate-love", "Marvel", "Medium", ["HATE", "LATE", "LAKE", "LIKE", "LIFE", "LIVE", "LOVE"]),
    makeLadder("fresh-east-mess", "General", "Medium", ["EAST", "LAST", "LOST", "MOST", "MIST", "MISS", "MESS"]),
    makeLadder("fresh-pass-last", "College Life", "Medium", ["PASS", "MASS", "MISS", "MIST", "MOST", "LOST", "LAST"]),
    makeLadder("fresh-head-send", "Science", "Medium", ["HEAD", "HEAL", "HEAT", "SEAT", "SENT", "SEND"]),
    makeLadder("fresh-ball-tent", "General", "Medium", ["BALL", "BELL", "BELT", "BEST", "REST", "RENT", "TENT"])
  ];

  if (typeof module !== "undefined" && module.exports) {
    module.exports = crossclimbDatabase;
  } else {
    globalScope.CROSSCLIMB_DATA = crossclimbDatabase;
  }
})(typeof globalThis !== "undefined" ? globalThis : window);
