(function exposeGameData(globalScope) {
  "use strict";

  const hangmanWords = [
    { id: "hm-javascript", answer: "JAVASCRIPT", category: "Technology", difficulty: "Easy", hint: "The main programming language used to make web pages interactive." },
    { id: "hm-algorithm", answer: "ALGORITHM", category: "Technology", difficulty: "Easy", hint: "A step-by-step method for solving a problem." },
    { id: "hm-database", answer: "DATABASE", category: "Technology", difficulty: "Easy", hint: "An organized collection where applications store and retrieve information." },
    { id: "hm-python", answer: "PYTHON", category: "Technology", difficulty: "Easy", hint: "A beginner-friendly programming language named after a comedy group." },
    { id: "hm-github", answer: "GITHUB", category: "Technology", difficulty: "Easy", hint: "A popular website for hosting code repositories and collaborating on projects." },
    { id: "hm-debugger", answer: "DEBUGGER", category: "Technology", difficulty: "Medium", hint: "A tool that pauses a program so developers can find mistakes." },
    { id: "hm-framework", answer: "FRAMEWORK", category: "Technology", difficulty: "Medium", hint: "A reusable structure that helps developers build applications faster." },
    { id: "hm-recursion", answer: "RECURSION", category: "Technology", difficulty: "Medium", hint: "A programming technique where a function calls itself." },
    { id: "hm-variable", answer: "VARIABLE", category: "Technology", difficulty: "Easy", hint: "A named place used to hold a value in a program." },
    { id: "hm-compiler", answer: "COMPILER", category: "Technology", difficulty: "Medium", hint: "Software that translates source code into a form a computer can run." },
    { id: "hm-network", answer: "NETWORK", category: "Technology", difficulty: "Easy", hint: "A group of connected devices that exchange information." },
    { id: "hm-protocol", answer: "PROTOCOL", category: "Technology", difficulty: "Medium", hint: "An agreed set of rules that lets computers communicate." },
    { id: "hm-process", answer: "PROCESS", category: "Technology", difficulty: "Medium", hint: "A program that is currently running on an operating system." },
    { id: "hm-thread", answer: "THREAD", category: "Technology", difficulty: "Medium", hint: "A smaller path of execution that runs inside a process." },
    { id: "hm-deadlock", answer: "DEADLOCK", category: "Technology", difficulty: "Medium", hint: "A standstill where programs keep waiting for resources held by each other." },
    { id: "hm-mutex", answer: "MUTEX", category: "Technology", difficulty: "Medium", hint: "A lock used to stop multiple threads from changing shared data at once." },
    { id: "hm-semaphore", answer: "SEMAPHORE", category: "Technology", difficulty: "Medium", hint: "An operating-system tool used to control access to shared resources." },
    { id: "hm-kernel", answer: "KERNEL", category: "Technology", difficulty: "Medium", hint: "The central part of an operating system that manages hardware and programs." },
    { id: "hm-memory", answer: "MEMORY", category: "Technology", difficulty: "Easy", hint: "The working space a computer uses while programs are running." },
    { id: "hm-cache", answer: "CACHE", category: "Technology", difficulty: "Easy", hint: "Fast temporary storage that keeps frequently used data close by." },
    { id: "hm-binary", answer: "BINARY", category: "Technology", difficulty: "Easy", hint: "A number system that uses only zero and one." },
    { id: "hm-hashing", answer: "HASHING", category: "Technology", difficulty: "Medium", hint: "Turning data into a fixed-size value for quick lookup or checking." },
    { id: "hm-encryption", answer: "ENCRYPTION", category: "Technology", difficulty: "Medium", hint: "Scrambling information so only authorized people can read it." },
    { id: "hm-sandbox", answer: "SANDBOX", category: "Technology", difficulty: "Easy", hint: "An isolated environment where code can run more safely." },
    { id: "hm-function", answer: "FUNCTION", category: "Technology", difficulty: "Easy", hint: "A reusable block of code that performs a particular task." },
    { id: "hm-object", answer: "OBJECT", category: "Technology", difficulty: "Easy", hint: "A programming value that can group related data and behavior." },
    { id: "hm-interface", answer: "INTERFACE", category: "Technology", difficulty: "Easy", hint: "The place where a person or one system interacts with another system." },
    { id: "hm-browser", answer: "BROWSER", category: "Technology", difficulty: "Easy", hint: "An app used to visit and interact with websites." },
    { id: "hm-server", answer: "SERVER", category: "Technology", difficulty: "Easy", hint: "A computer or program that provides data and services to others." },
    { id: "hm-client", answer: "CLIENT", category: "Technology", difficulty: "Easy", hint: "A device or program that requests a service from a server." },
    { id: "hm-cloud", answer: "CLOUD", category: "Technology", difficulty: "Easy", hint: "Remote internet-based computing and storage services." },
    { id: "hm-router", answer: "ROUTER", category: "Technology", difficulty: "Easy", hint: "A device that directs network traffic between your devices and the internet." },
    { id: "hm-firewall", answer: "FIREWALL", category: "Technology", difficulty: "Easy", hint: "A security barrier that filters incoming and outgoing network traffic." },
    { id: "hm-software", answer: "SOFTWARE", category: "Technology", difficulty: "Easy", hint: "The programs and instructions that run on a computer." },
    { id: "hm-hardware", answer: "HARDWARE", category: "Technology", difficulty: "Easy", hint: "The physical parts of a computer that you can touch." },
    { id: "hm-website", answer: "WEBSITE", category: "Technology", difficulty: "Easy", hint: "A collection of related pages you visit through a browser." },
    { id: "hm-keyboard", answer: "KEYBOARD", category: "Technology", difficulty: "Easy", hint: "The input device with letter, number, and function keys." },
    { id: "hm-pixel", answer: "PIXEL", category: "Technology", difficulty: "Easy", hint: "The smallest individual dot of color in a digital image." },
    { id: "hm-robot", answer: "ROBOT", category: "Technology", difficulty: "Easy", hint: "A programmable machine that can carry out physical tasks." },
    { id: "hm-coding", answer: "CODING", category: "Technology", difficulty: "Easy", hint: "The activity of writing instructions for computers." },

    { id: "hm-multiverse", answer: "MULTIVERSE", category: "Marvel", difficulty: "Easy", hint: "A collection of alternate universes where different versions of heroes can exist." },
    { id: "hm-webshooter", answer: "WEBSHOOTER", category: "Spider-Man", difficulty: "Easy", hint: "The wrist gadget Spider-Man uses to fire artificial webs." },
    { id: "hm-symbiote", answer: "SYMBIOTE", category: "Spider-Man", difficulty: "Medium", hint: "An alien life-form that bonds with a host, as Venom does." },
    { id: "hm-oscorp", answer: "OSCORP", category: "Spider-Man", difficulty: "Medium", hint: "The powerful company associated with Norman Osborn." },
    { id: "hm-stark", answer: "STARK", category: "Marvel", difficulty: "Easy", hint: "The surname of Marvel's billionaire inventor in the iron suit." },
    { id: "hm-reactor", answer: "REACTOR", category: "Marvel", difficulty: "Easy", hint: "The arc-powered energy device linked to Iron Man's technology." },
    { id: "hm-spiderverse", answer: "SPIDERVERSE", category: "Spider-Man", difficulty: "Easy", hint: "The shared web of realities containing many different Spider heroes." },
    { id: "hm-morales", answer: "MORALES", category: "Spider-Man", difficulty: "Easy", hint: "The surname of the Spider-Man named Miles." },
    { id: "hm-parker", answer: "PARKER", category: "Spider-Man", difficulty: "Easy", hint: "The surname of the original friendly neighborhood Spider-Man." },
    { id: "hm-gwen", answer: "GWEN", category: "Spider-Man", difficulty: "Easy", hint: "The first name of the drummer who becomes Spider-Woman in another universe." },
    { id: "hm-venom", answer: "VENOM", category: "Spider-Man", difficulty: "Easy", hint: "The black symbiote antihero famous for sharp teeth and a long tongue." },
    { id: "hm-carnage", answer: "CARNAGE", category: "Spider-Man", difficulty: "Easy", hint: "The dangerous red symbiote created from Venom's offspring." },
    { id: "hm-mysterio", answer: "MYSTERIO", category: "Spider-Man", difficulty: "Medium", hint: "A Spider-Man villain known for illusions and a fishbowl-like helmet." },
    { id: "hm-electro", answer: "ELECTRO", category: "Spider-Man", difficulty: "Easy", hint: "A Spider-Man villain who can control electricity." },
    { id: "hm-octavius", answer: "OCTAVIUS", category: "Spider-Man", difficulty: "Medium", hint: "The surname of the doctor who fights using four mechanical tentacles." },
    { id: "hm-jarvis", answer: "JARVIS", category: "Marvel", difficulty: "Easy", hint: "The name of Tony Stark's helpful artificial intelligence." },
    { id: "hm-vibranium", answer: "VIBRANIUM", category: "Marvel", difficulty: "Medium", hint: "The rare Wakandan metal used in Black Panther's suit and Captain America's shield." },
    { id: "hm-nanotech", answer: "NANOTECH", category: "Marvel", difficulty: "Medium", hint: "Extremely tiny technology used in some of Iron Man's advanced suits." },
    { id: "hm-avengers", answer: "AVENGERS", category: "Marvel", difficulty: "Easy", hint: "The superhero team that assembles to face threats too large for one hero." },
    { id: "hm-wakanda", answer: "WAKANDA", category: "Marvel", difficulty: "Easy", hint: "The hidden African nation protected by Black Panther." },
    { id: "hm-asgard", answer: "ASGARD", category: "Marvel", difficulty: "Easy", hint: "The legendary realm that Thor calls home." },
    { id: "hm-mjolnir", answer: "MJOLNIR", category: "Marvel", difficulty: "Medium", hint: "Thor's enchanted hammer, which can be lifted only by the worthy." },
    { id: "hm-groot", answer: "GROOT", category: "Marvel", difficulty: "Easy", hint: "The tree-like Guardian of the Galaxy with a very limited vocabulary." },
    { id: "hm-rocket", answer: "ROCKET", category: "Marvel", difficulty: "Easy", hint: "The clever, weapon-loving raccoon in the Guardians of the Galaxy." },
    { id: "hm-gamora", answer: "GAMORA", category: "Marvel", difficulty: "Easy", hint: "The green-skinned Guardian raised by Thanos." },
    { id: "hm-thanos", answer: "THANOS", category: "Marvel", difficulty: "Easy", hint: "The villain who collects the Infinity Stones for his gauntlet." },
    { id: "hm-nebula", answer: "NEBULA", category: "Marvel", difficulty: "Easy", hint: "Gamora's blue-skinned cyborg sister." },
    { id: "hm-daredevil", answer: "DAREDEVIL", category: "Marvel", difficulty: "Easy", hint: "The blind lawyer who protects Hell's Kitchen at night." },
    { id: "hm-panther", answer: "PANTHER", category: "Marvel", difficulty: "Easy", hint: "The animal in the superhero title held by Wakanda's protector." },
    { id: "hm-marvel", answer: "MARVEL", category: "Marvel", difficulty: "Easy", hint: "The entertainment company behind Spider-Man, the Avengers, and the X-Men." },

    { id: "hm-acm", answer: "ACM", category: "ACM & R&D", difficulty: "Easy", hint: "A major international association for computing professionals and students." },
    { id: "hm-research", answer: "RESEARCH", category: "ACM & R&D", difficulty: "Easy", hint: "Careful investigation performed to discover or verify knowledge." },
    { id: "hm-prototype", answer: "PROTOTYPE", category: "ACM & R&D", difficulty: "Easy", hint: "An early working version built to test an idea." },
    { id: "hm-innovation", answer: "INNOVATION", category: "ACM & R&D", difficulty: "Medium", hint: "A useful new idea, method, or product." },
    { id: "hm-experiment", answer: "EXPERIMENT", category: "ACM & R&D", difficulty: "Easy", hint: "A controlled test used to investigate a question." },
    { id: "hm-hypothesis", answer: "HYPOTHESIS", category: "ACM & R&D", difficulty: "Medium", hint: "A testable explanation proposed before an experiment." },
    { id: "hm-analysis", answer: "ANALYSIS", category: "ACM & R&D", difficulty: "Easy", hint: "A detailed examination of information to understand what it means." },
    { id: "hm-dataset", answer: "DATASET", category: "ACM & R&D", difficulty: "Easy", hint: "A structured collection of related data used for study or training." },
    { id: "hm-journal", answer: "JOURNAL", category: "ACM & R&D", difficulty: "Easy", hint: "A publication where researchers share reviewed academic work." },
    { id: "hm-conference", answer: "CONFERENCE", category: "ACM & R&D", difficulty: "Easy", hint: "An event where researchers present work and exchange ideas." },
    { id: "hm-workshop", answer: "WORKSHOP", category: "ACM & R&D", difficulty: "Easy", hint: "A practical session where a group learns or builds something together." },
    { id: "hm-abstract", answer: "ABSTRACT", category: "ACM & R&D", difficulty: "Medium", hint: "A short summary placed at the beginning of a research paper." },
    { id: "hm-citation", answer: "CITATION", category: "ACM & R&D", difficulty: "Medium", hint: "A reference that credits the source of an idea or fact." },
    { id: "hm-poster", answer: "POSTER", category: "ACM & R&D", difficulty: "Easy", hint: "A large visual display often used to present research at an event." },
    { id: "hm-survey", answer: "SURVEY", category: "ACM & R&D", difficulty: "Easy", hint: "A set of questions used to collect information from people." },
    { id: "hm-sample", answer: "SAMPLE", category: "ACM & R&D", difficulty: "Easy", hint: "A smaller group or portion selected to represent a larger whole." },
    { id: "hm-metric", answer: "METRIC", category: "ACM & R&D", difficulty: "Medium", hint: "A measurement used to judge performance or progress." },
    { id: "hm-model", answer: "MODEL", category: "ACM & R&D", difficulty: "Easy", hint: "A simplified representation used to explain or predict something." },
    { id: "hm-design", answer: "DESIGN", category: "ACM & R&D", difficulty: "Easy", hint: "The planned structure and appearance of a product or experiment." },
    { id: "hm-testing", answer: "TESTING", category: "ACM & R&D", difficulty: "Easy", hint: "The process of checking whether something works as intended." },
    { id: "hm-discovery", answer: "DISCOVERY", category: "ACM & R&D", difficulty: "Easy", hint: "Finding something important that was not known before." },
    { id: "hm-laboratory", answer: "LABORATORY", category: "Science", difficulty: "Easy", hint: "A room equipped for scientific experiments and measurements." },
    { id: "hm-science", answer: "SCIENCE", category: "Science", difficulty: "Easy", hint: "The systematic study of the natural world through evidence." },
    { id: "hm-physics", answer: "PHYSICS", category: "Science", difficulty: "Easy", hint: "The science of matter, energy, motion, and forces." },
    { id: "hm-chemistry", answer: "CHEMISTRY", category: "Science", difficulty: "Easy", hint: "The science that studies substances and how they react." },
    { id: "hm-biology", answer: "BIOLOGY", category: "Science", difficulty: "Easy", hint: "The science that studies living organisms." },
    { id: "hm-quantum", answer: "QUANTUM", category: "Science", difficulty: "Medium", hint: "A word linked to the physics of particles at extremely small scales." },
    { id: "hm-gravity", answer: "GRAVITY", category: "Science", difficulty: "Easy", hint: "The force that pulls objects toward one another and keeps us on Earth." },
    { id: "hm-energy", answer: "ENERGY", category: "Science", difficulty: "Easy", hint: "The ability to do work or cause change." },
    { id: "hm-circuit", answer: "CIRCUIT", category: "Science", difficulty: "Easy", hint: "A complete path through which electric current can flow." },

    { id: "hm-orange", answer: "ORANGE", category: "General", difficulty: "Easy", hint: "A citrus fruit and a color between red and yellow." },
    { id: "hm-planet", answer: "PLANET", category: "General", difficulty: "Easy", hint: "A large round object that travels around a star." },
    { id: "hm-library", answer: "LIBRARY", category: "General", difficulty: "Easy", hint: "A place where books and other learning resources are collected." },
    { id: "hm-mountain", answer: "MOUNTAIN", category: "General", difficulty: "Easy", hint: "A natural landform that rises much higher than the surrounding ground." },
    { id: "hm-ocean", answer: "OCEAN", category: "General", difficulty: "Easy", hint: "A vast body of salt water covering much of Earth." },
    { id: "hm-compass", answer: "COMPASS", category: "General", difficulty: "Easy", hint: "A tool with a needle that helps travelers find direction." },
    { id: "hm-calendar", answer: "CALENDAR", category: "General", difficulty: "Easy", hint: "A chart or app that organizes days, weeks, and months." },
    { id: "hm-journey", answer: "JOURNEY", category: "General", difficulty: "Easy", hint: "Travel from one place to another, often over some distance." },
    { id: "hm-puzzle", answer: "PUZZLE", category: "General", difficulty: "Easy", hint: "A problem or game designed to test clever thinking." },
    { id: "hm-courage", answer: "COURAGE", category: "General", difficulty: "Easy", hint: "The strength to face fear or difficulty." },
    { id: "hm-friendship", answer: "FRIENDSHIP", category: "General", difficulty: "Easy", hint: "A caring relationship between people who trust and support one another." },
    { id: "hm-music", answer: "MUSIC", category: "General", difficulty: "Easy", hint: "Organized sound made with voices or instruments." },
    { id: "hm-cinema", answer: "CINEMA", category: "Movies & Pop Culture", difficulty: "Easy", hint: "The art of movies or the place where they are shown." },
    { id: "hm-football", answer: "FOOTBALL", category: "General", difficulty: "Easy", hint: "A team sport played with a ball, goals, and a large field." },
    { id: "hm-chocolate", answer: "CHOCOLATE", category: "General", difficulty: "Easy", hint: "A sweet food made from roasted cacao beans." },
    { id: "hm-umbrella", answer: "UMBRELLA", category: "General", difficulty: "Easy", hint: "A folding cover held above the head to block rain or sun." },
    { id: "hm-airport", answer: "AIRPORT", category: "General", difficulty: "Easy", hint: "A place where passenger planes arrive and depart." },
    { id: "hm-backpack", answer: "BACKPACK", category: "College Life", difficulty: "Easy", hint: "A bag carried on both shoulders, often filled with books and a laptop." },
    { id: "hm-rainbow", answer: "RAINBOW", category: "General", difficulty: "Easy", hint: "A curved band of colors sometimes visible after rain." },
    { id: "hm-volcano", answer: "VOLCANO", category: "General", difficulty: "Easy", hint: "A mountain that can erupt with lava, ash, and gas." }
  ];

  function ladder(id, category, difficulty, words, clues) {
    return {
      id,
      category,
      difficulty,
      startWord: words[0],
      endWord: words[words.length - 1],
      ladder: words,
      clues
    };
  }

  const crossclimbDatabase = [
    ladder("cc-cat-dog", "General", "Easy", ["CAT", "COT", "DOT", "DOG"], ["A common pet that purrs.", "A small portable bed.", "A tiny round mark.", "A common pet that barks."]),
    ladder("cc-cold-warm", "General", "Easy", ["COLD", "CORD", "CARD", "WARD", "WARM"], ["Low in temperature.", "A thick string or electrical cable.", "A small piece of stiff paper used for messages or games.", "A section of a hospital.", "Comfortably hot rather than cold."]),
    ladder("cc-head-tail", "General", "Medium", ["HEAD", "HEAL", "TEAL", "TELL", "TALL", "TAIL"], ["The top part of your body.", "To become healthy again.", "A blue-green color.", "To communicate something with words.", "Having greater than average height.", "The rear part of many animals."]),
    ladder("cc-lead-gold", "Science", "Easy", ["LEAD", "LOAD", "GOAD", "GOLD"], ["A heavy metal with the symbol Pb.", "Something carried or transported.", "To provoke someone into action.", "A valuable yellow metal."]),
    ladder("cc-fool-sage", "General", "Medium", ["FOOL", "POOL", "POLL", "POLE", "PALE", "SALE", "SAGE"], ["A person who acts without good judgment.", "A place built for swimming.", "A survey used to collect opinions.", "A long, slender post.", "Light in color or lacking healthy color.", "A period when goods are sold for less.", "A very wise person or a fragrant herb."]),
    ladder("cc-fire-cold", "General", "Easy", ["FIRE", "FARE", "CARE", "CORE", "CORD", "COLD"], ["Flames that produce heat and light.", "The price paid for a ride.", "Concern and attention given to someone or something.", "The central part of something.", "A thick string or electrical cable.", "Low in temperature."]),
    ladder("cc-east-west", "General", "Easy", ["EAST", "LAST", "LEST", "BEST", "WEST"], ["The direction where the sun rises.", "Coming after all others.", "A word meaning 'to avoid the risk that.'", "Better than all the rest.", "The direction where the sun sets."]),
    ladder("cc-rich-poor", "General", "Medium", ["RICH", "RICK", "ROCK", "ROOK", "COOK", "COOL", "POOL", "POOR"], ["Having a great deal of money or resources.", "A stack of hay or a person's first name.", "A solid piece of stone.", "A castle-shaped chess piece.", "To prepare food with heat.", "Slightly cold or impressively stylish.", "A place built for swimming.", "Having very little money."]),
    ladder("cc-cup-mug", "General", "Easy", ["CUP", "CUB", "RUB", "RUG", "MUG"], ["A small container used for drinking.", "A young bear, lion, or fox.", "To move your hand back and forth over a surface.", "A small carpet.", "A large cup, often used for coffee."]),
    ladder("cc-car-bus", "General", "Easy", ["CAR", "BAR", "BAT", "BUT", "BUS"], ["A road vehicle for a few passengers.", "A counter where drinks are served.", "An animal that flies at night, or sports equipment used to hit a ball.", "A word used to introduce a contrast.", "A large road vehicle carrying many passengers."]),
    ladder("cc-sea-sky", "Science", "Easy", ["SEA", "SET", "SAT", "SAY", "SKY"], ["A large body of salt water.", "To place something in position.", "Took a seat.", "To speak words aloud.", "The space seen above Earth."]),
    ladder("cc-top-low", "General", "Easy", ["TOP", "COP", "COW", "LOW"], ["The highest part of something.", "An informal word for a police officer.", "A farm animal that gives milk.", "Not high or below the usual level."]),
    ladder("cc-time-date", "General", "Easy", ["TIME", "DIME", "DAME", "DARE", "DATE"], ["What clocks measure.", "A United States coin worth ten cents.", "A formal title for a woman.", "To be brave enough to try something.", "A particular day on the calendar."]),
    ladder("cc-love-kind", "General", "Medium", ["LOVE", "MOVE", "MORE", "MARE", "MATE", "MITE", "MINE", "MIND", "KIND"], ["Deep affection for someone or something.", "To change position.", "A greater amount.", "An adult female horse.", "A friend, partner, or matching piece.", "A very small creature related to spiders.", "Something that belongs to me, or a place where minerals are dug up.", "The part of a person that thinks.", "Caring and helpful toward others."]),
    ladder("cc-rain-snow", "Science", "Hard", ["RAIN", "RAID", "SAID", "SAIL", "SOIL", "TOIL", "TOOL", "POOL", "FOOL", "FOOT", "BOOT", "BLOT", "SLOT", "SLOW", "SNOW"], ["Water drops falling from clouds.", "A sudden attack or search.", "Spoke words in the past.", "A sheet that catches wind to move a boat.", "The upper layer of earth where plants grow.", "To work very hard for a long time.", "An object used to perform a task.", "A place built for swimming.", "A person who acts without good judgment.", "The body part at the end of your leg.", "A sturdy shoe that covers the ankle.", "A spot or mark made by spilled liquid.", "A narrow opening or scheduled position.", "Moving at a low speed.", "Soft white ice crystals that fall from clouds."]),

    ladder("cc-code-data", "Technology", "Easy", ["CODE", "NODE", "MODE", "MADE", "MATE", "DATE", "DATA"], ["Instructions written for a computer.", "A point in a network or linked structure.", "A particular operating setting.", "Created or built in the past.", "A friend, partner, or matching piece.", "A particular day on the calendar.", "Facts and information stored for use."]),
    ladder("cc-byte-bios", "Technology", "Medium", ["BYTE", "BITE", "SITE", "SITS", "BITS", "BIOS"], ["A computing unit made of eight bits.", "To cut with the teeth.", "A location, especially one on the web.", "Takes a seat.", "The smallest binary data units.", "Firmware that starts a computer before the operating system loads."]),
    ladder("cc-game-code", "Technology", "Easy", ["GAME", "CAME", "CANE", "CONE", "CODE"], ["An activity played for fun or competition.", "Arrived in the past.", "A walking stick or tall plant stem.", "A shape with a circular base and pointed top.", "Instructions written for a computer."]),
    ladder("cc-bug-fix", "Technology", "Easy", ["BUG", "BIG", "FIG", "FIX"], ["An insect, or an error in a program.", "Large in size.", "A soft, sweet fruit filled with tiny seeds.", "To repair a problem."]),
    ladder("cc-ram-rom", "Technology", "Easy", ["RAM", "RIM", "ROM"], ["Fast working memory used by active programs.", "The outer edge of a wheel or cup.", "Computer memory that is normally read rather than changed."]),
    ladder("cc-hack-safe", "Technology", "Medium", ["HACK", "SACK", "SICK", "SINK", "SINE", "SANE", "SAFE"], ["To gain unauthorized access, or a clever quick solution.", "A large strong bag.", "Ill or unwell.", "A basin with a drain, or to move downward.", "A wave-related function used in mathematics.", "Having a healthy and reasonable mind.", "Protected from danger."]),
    ladder("cc-home-work", "Technology", "Easy", ["HOME", "COME", "CORE", "CORK", "WORK"], ["The place where someone lives.", "To move toward a place.", "The central part of something.", "The light material used to seal many bottles.", "An activity that requires effort, including coding."]),
    ladder("cc-food-cook", "Technology", "Medium", ["FOOD", "MOOD", "MOLD", "COLD", "CORD", "CORE", "CORK", "COOK"], ["What people eat for energy.", "A person's current emotional state.", "A hollow shape used to form an object, or a type of fungus.", "Low in temperature.", "A thick string or electrical cable.", "The central part of something.", "The light material used to seal many bottles.", "To prepare food with heat."]),

    ladder("cc-mind-mask", "Marvel", "Medium", ["MIND", "WIND", "WING", "RING", "RINK", "RANK", "TANK", "TASK", "MASK"], ["The part of a person that thinks.", "Moving air.", "A body part used by birds and Falcon to fly.", "A circular band worn as jewelry.", "An ice surface used for skating.", "A position in an ordered list.", "A heavy armored vehicle.", "A piece of work that must be completed.", "A face covering used to hide an identity."]),
    ladder("cc-park-punk", "Spider-Man", "Easy", ["PARK", "BARK", "BANK", "BUNK", "PUNK"], ["A public green space; it also begins Peter's surname.", "The outer covering of a tree.", "A place that keeps and lends money.", "A narrow bed, often stacked above another.", "A rebellious music style linked to Spider-Punk."]),
    ladder("cc-web-bug", "Spider-Man", "Easy", ["WEB", "WET", "BET", "BAT", "BAG", "BUG"], ["A spider's silken net.", "Covered with water.", "Money risked on an uncertain result.", "A flying mammal active at night.", "A container made of flexible material.", "A small insect, or an error in software."]),
    ladder("cc-hero-mask", "Marvel", "Medium", ["HERO", "HERE", "HIRE", "FIRE", "FARE", "CARE", "CASE", "CASK", "MASK"], ["A brave person admired for great actions.", "In this place.", "To employ someone for a job.", "Flames that produce heat and light.", "The price paid for a ride.", "Concern and attention given to someone or something.", "A container or an example under study.", "A barrel used to store liquid.", "A face covering used to hide an identity."]),
    ladder("cc-bite-hero", "Spider-Man", "Medium", ["BITE", "BITS", "BATS", "HATS", "HATE", "HARE", "HERE", "HERO"], ["What the radioactive spider did to Peter Parker.", "Small binary data units.", "Flying mammals active at night.", "Head coverings.", "A strong feeling of dislike.", "A fast-running animal like a large rabbit.", "In this place.", "A brave person admired for great actions."]),

    ladder("cc-heat-cold", "Science", "Medium", ["HEAT", "HEAD", "LEAD", "LOAD", "GOAD", "GOLD", "COLD"], ["Thermal energy that raises temperature.", "The top part of your body.", "A heavy metal with the symbol Pb.", "Something carried or transported.", "To provoke someone into action.", "A valuable yellow metal.", "Low in temperature."]),
    ladder("cc-moon-star", "Science", "Hard", ["MOON", "SOON", "SOOT", "SHOT", "SLOT", "SLAT", "SLAY", "STAY", "STAR"], ["Earth's natural satellite.", "After a short amount of time.", "Black powder left by smoke.", "A single attempt or a fired projectile.", "A narrow opening or scheduled position.", "A thin, flat strip of wood or metal.", "To defeat completely.", "To remain in one place.", "A glowing ball of gas in space."]),
    ladder("cc-dust-star", "Science", "Medium", ["DUST", "MUST", "MAST", "MALT", "MOLT", "MOOT", "BOOT", "BLOT", "SLOT", "SLAT", "SLAY", "STAY", "STAR"], ["Fine dry particles found on surfaces.", "Something that is required.", "A tall pole supporting a ship's sails.", "Grain prepared for brewing or food.", "To shed old feathers, skin, or hair.", "No longer important enough to debate, or a practice discussion.", "A sturdy shoe that covers the ankle.", "A spot or mark made by spilled liquid.", "A narrow opening or scheduled position.", "A thin, flat strip of wood or metal.", "To defeat completely.", "To remain in one place.", "A glowing ball of gas in space."]),
    ladder("cc-gene-cell", "Science", "Hard", ["GENE", "GONE", "TONE", "TOTE", "MOTE", "MATE", "MALE", "MALT", "MELT", "BELT", "BELL", "CELL"], ["A unit of inherited biological information.", "No longer present.", "The quality or pitch of a sound.", "To carry something, or a large reusable bag.", "A tiny particle, especially a speck of dust.", "A friend, partner, or matching piece.", "A word describing a boy, man, or male animal.", "Grain prepared for brewing or food.", "To change from solid to liquid through heat.", "A strip worn around the waist.", "A hollow metal object that rings.", "The basic structural unit of living things."]),

    ladder("cc-test-mock", "R&D", "Medium", ["TEST", "TENT", "TINT", "MINT", "MIND", "MINK", "MONK", "MOCK"], ["A check used to see whether something works.", "A portable fabric shelter.", "A light shade of a color.", "A fresh-tasting herb or a place that makes coins.", "The part of a person that thinks.", "A small animal valued for its soft fur.", "A member of a religious community.", "A practice version or imitation used for testing."]),
    ladder("cc-test-pass", "R&D", "Easy", ["TEST", "BEST", "BEAT", "MEAT", "MELT", "MALT", "MAST", "MASS", "PASS"], ["A check used to see whether something works.", "Better than all the rest.", "To strike repeatedly or defeat in a contest.", "Animal flesh used as food.", "To change from solid to liquid through heat.", "Grain prepared for brewing or food.", "A tall pole supporting a ship's sails.", "The amount of matter in an object.", "To meet the required standard."]),
    ladder("cc-fail-pass", "College Life", "Easy", ["FAIL", "FALL", "MALL", "MALT", "MAST", "MASS", "PASS"], ["To not meet the required standard.", "To move downward because of gravity.", "A large indoor shopping center.", "Grain prepared for brewing or food.", "A tall pole supporting a ship's sails.", "The amount of matter in an object.", "To meet the required standard."]),
    ladder("cc-book-read", "College Life", "Easy", ["BOOK", "BOOM", "ROOM", "ROAM", "ROAD", "READ"], ["A set of written or printed pages.", "A deep, loud sound or a rapid rise.", "An area inside a building.", "To travel without a fixed route.", "A paved route for vehicles.", "To understand written words."]),
    ladder("cc-cafe-home", "College Life", "Easy", ["CAFE", "CANE", "CONE", "COME", "HOME"], ["A small restaurant serving drinks and light meals.", "A walking stick or tall plant stem.", "A shape with a circular base and pointed top.", "To move toward a place.", "The place where someone lives."]),
    ladder("cc-dorm-home", "College Life", "Easy", ["DORM", "FORM", "FORK", "CORK", "CORE", "COME", "HOME"], ["A student residence building.", "The shape or structure of something.", "A table utensil with pointed prongs.", "The light material used to seal many bottles.", "The central part of something.", "To move toward a place.", "The place where someone lives."]),

    ladder("cc-film-star", "Movies & Pop Culture", "Hard", ["FILM", "FIRM", "FARM", "WARM", "WARD", "CARD", "CORD", "COLD", "GOLD", "TOLD", "TOAD", "ROAD", "ROAM", "ROOM", "BOOM", "BOOR", "BOAR", "SOAR", "SCAR", "STAR"], ["A movie or a thin layer of material.", "Strong and steady, or a business company.", "Land used to grow crops or raise animals.", "Comfortably hot rather than cold.", "A section of a hospital.", "A small piece of stiff paper used for messages or games.", "A thick string or electrical cable.", "Low in temperature.", "A valuable yellow metal.", "Communicated something in the past.", "A short, wide animal related to frogs.", "A paved route for vehicles.", "To travel without a fixed route.", "An area inside a building.", "A deep, loud sound or a rapid rise.", "A rude or unpleasant person.", "A wild pig.", "To fly or rise high in the air.", "A mark left after a wound heals.", "A famous performer or a glowing ball of gas."]),
    ladder("cc-song-band", "Movies & Pop Culture", "Easy", ["SONG", "LONG", "LONE", "LANE", "LAND", "BAND"], ["A short piece of music with words.", "Measuring a great distance from end to end.", "Alone or without companions.", "A marked strip of road for one line of traffic.", "Solid ground rather than water.", "A group of musicians who perform together."]),
    ladder("cc-rock-band", "Movies & Pop Culture", "Easy", ["ROCK", "RACK", "BACK", "BANK", "BAND"], ["A music style driven by guitars and drums.", "A frame used to hold or store items.", "The rear side of something.", "A place that keeps and lends money.", "A group of musicians who perform together."])
  ];

  const gameData = Object.freeze({ hangmanWords, crossclimbDatabase });

  if (typeof module !== "undefined" && module.exports) {
    module.exports = gameData;
  } else {
    globalScope.GAME_DATA = gameData;
  }
})(typeof globalThis !== "undefined" ? globalThis : window);
